### ISSUE TITLE
Syntax Errors in Script

### ISSUE THREAD

**Issue by ghost** [SlippingGitty/Linux-Surface-Wizard#9]
When running the bash command for Debian based distros, I receive the following errors and the script is aborted:

**/dev/fd/63: line 29: syntax error near unexpected token 'do'
/dev/fd/63: line 29: '@@ -35,48 +32,66 @@ while [ "$CHOICE -ne 4" ]; do'**

I'm currently running Linux Mint 20.2 on a Surface Pro 4 with all dependencies installed and root password set.

**Comment by SlippingGitty** [comment]
Hi there! I apologize about that. This is entirely a fault on my part, which I have fixed just now. If you bump into any issues again, please tell me as soon as you can.

**Comment by ghost** [comment]
Thanks very much.  It's getting further, but is now erroring out on a different line:

**/dev/fd/63: line 51: d: command not found**

Looks like there's a misplaced tab in the middle of the word "**dialog**"

**Comment by SlippingGitty** [comment]
Thank you once again, I apologize for the inconvenience. I will do some more troubleshooting later today. In the mean time, I have removed the misplaced tab.
